import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
// state variable for a form containg a straing and a number

//  a function which makes a post request to backend send the form data and receiving back the message

const Home: NextPage = () => {
  const [srn, setSrn] = useState("");
  const [prefix, setPrefix] = useState("");
  const [message, setMessage] = useState("");
  // handle submit which makes a post request to backend sending srn and prefix in json form and receiving back the message
  const handleSubmit = (e: { preventDefault: () => void; }) => {
    e.preventDefault();
    const data = { "srn":srn, "prefix":prefix};
    void fetch("https://registrations.sakshamalok.repl.co/attended", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    })
      .then((res) => res.json())
      .then((data) => {
        // eslint-disable-next-line @typescript-eslint/no-unsafe-argument, @typescript-eslint/no-unsafe-member-access
        setMessage(data.message);
        setSrn("");
      });
      
  };

  return (
    <>
      <Head>
        <title>Registrations</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Registrations by{" "}
            <span className="text-[hsl(280,100%,70%)]">Hackerspace</span>
          </h1>
          
          
          <form className="flex flex-col items-center justify-center gap-4 w-full max-w-[30rem]">
            <div className="flex flex-col items-start justify-start w-full">

              <label htmlFor="srn" className="text-lg font-medium text-white">
                SRN
              </label>
              <select id="underline_select"  value={prefix} onChange={(e) => {
                setPrefix(e.target.value)}} name= "prefix" className="block py-2.5 px-0 w-full text-sm text-gray-500 bg-transparent border-0 border-b-2 border-gray-200 appearance-none dark:text-gray-400 dark:border-gray-700 focus:outline-none focus:ring-0 focus:border-gray-200 peer">
              
              <option selected value="PES2UG22">EC Campus First Year</option>
              <option value="PES2UG21">EC Campus Second Year</option>
              <option value="PES1UG22">RR Campus First Year</option>
              <option value="PES1UG21">RR Campus Second Year</option>
          </select>
              <input
                type="text"
                name="srn"
                id="srn"
                className="w-full px-4 py-2 mt-2 text-lg font-medium text-white bg-purple-500 bg-opacity-10 bg-clip-padding backdrop-blur-sm backdrop-filter rounded-md focus:outline-none focus:ring-2 focus:ring-[hsl(280,100%,70%)] focus:ring-opacity-50"
                value={srn}
                placeholder="Last 5 characters"
                onChange={(e) => setSrn(e.target.value)}
              />

              </div>
              <div >
              <button type="button" onClick={handleSubmit} className="bg-clip-padding backdrop-filter   active:bg-violet-700 text-white transition-colors delay-100 hover:bg-[hsl(280,100%,70%)] rounded-lg py-2 px-8 backdrop-blur-xl bg-opacity-60 border">Present</button>
              </div>
              </form>
              <div className="text-lg font-medium text-white">
                {message}
                </div>
        </div>
      </main>
    </>
  );
};

export default Home;
